CAPS_WORD_ENABLE = yes

GROTA_TAPDANCE_BOOT = yes
GROTA_TAPDANCE_CLEAR_EEPROM = yes
GROTA_TAPDANCE_SET_DEFAULT_LAYER = yes
GROTA_ENABLE_NUMBERS_FN_KC = yes
GROTA_ENABLE_INVERTED_SHIFT_US_ANSI = yes

TAP_DANCE_ENABLE = yes
USER_NAME := grota

GROTA_CUSTOM_MEDIA_KC = no
include keyboards/grota_dactyl_manuform/5x7/rules_before_user.mk
