RGB_MATRIX_ENABLE = no
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = no
COMMAND_ENABLE   = no
CONSOLE_ENABLE   = no
RGBLIGHT_ENABLE = no
DEBOUNCE_TYPE = eager_pk

#OPT_DEFS += -DDISABLE_RGB_MATRIX_CYCLE_ALL
